name: Cypress Tests and Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Necessário para publicar no GitHub Pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm install -g allure-commandline

      - name: Run Cypress tests
        run: npm test

      - name: Generate Allure Report
        run: allure generate allure-results --clean

      - name: Load Allure Report History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages  # Diretório onde o histórico será salvo

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results  # Ajuste este caminho conforme sua configuração
          allure_history: allure-history

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
