name: Cypress Tests and Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm install -g allure-commandline

      - name: Run Cypress tests
        run: npm run test:cy

      # - name: Generate report
      #   run: npm run allure:report

      - name: Test Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            name: cypress-test-report
            path: allure-report/

      # - name: Download Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: cypress-test-report